#!/bin/bash

set -e
app=codiad

# Retrieve arguments
domain=$1
path=$2

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a $app  \
    || (echo "Path not available: $domain$path" && exit 1)

# Remove trailing "/"
path=${path%/}

# Copy sources
final_path=/var/www/$app
sudo mkdir -p $final_path
sudo cp -a ../sources/. $final_path

# Copy and edit config.php
sudo cp ../conf/config.php $final_path
sudo cp ../conf/codiad_http_auth.php $final_path
sudo sed -i "s/yuno_path/$domain$path/g" $final_path/config.php

# Set permissions to codiad and data directory
sudo chown -R root:root $final_path
sudo chown www-data:www-data $final_path/config.php
sudo chown -R www-data:www-data $final_path/data
sudo chown -R www-data:www-data $final_path/workspace
sudo chown -R www-data:www-data $final_path/plugins
sudo chown -R www-data:www-data $final_path/themes

# Use dedicated php pool
sed -i "s@NAMETOCHANGE@$app@g" ../conf/php-fpm.conf
finalphpconf=/etc/php5/fpm/pool.d/$app.conf
sudo cp ../conf/php-fpm.conf $finalphpconf
sudo chown root: $finalphpconf
sudo chmod 644 $finalphpconf

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@NAMETOCHANGE@$app@g" ../conf/nginx.conf*
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf*
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf*
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# Reload Nginx, PHP5-FPM and regenerate SSOwat conf
sudo service php5-fpm restart
sudo service nginx reload
sudo yunohost app ssowatconf