#!/bin/bash
app=codiad

# Retrieve arguments
domain=$(sudo yunohost app setting $app domain)

# Remove sources
sudo rm -rf /var/www/$app

# Remove configuration files
sudo rm -f /etc/nginx/conf.d/$domain.d/$app.conf
sudo rm -f /etc/php5/fpm/pool.d/$app.conf

# Restart services
sudo service php5-fpm restart
sudo service nginx reload
sudo yunohost app ssowatconf